language: go
go:
  - "1.10"
  - "1.11"
  - tip
sudo: false
install: true
matrix:
  include:
  - go: "1.10.x"
    script:  go test -v ./...
  - go: "1.11.x"
    script: scripts/ci.sh

env:
  global:
    - GO111MODULE=on
